### ISSUE TITLE
Issues running multi-sample VCF

### ISSUE THREAD

**Issue by holtjma** [hwanglab/divine#1]
Hello,

I'm trying to run divine on a multi-sample family VCF.  Looks like a PED file is required but the ones I have don't seem to be capable of loading into divine for some reason.  I've used the PED files for other software without issue.  Here's the exact error I'm getting:

```
Traceback (most recent call last):
  File "[MASKED]/divine/gcn/bin/prioritize/divine.py", line 1414, in <module>
    main()
  File "[MASKED]/divine/gcn/bin/prioritize/divine.py", line 1342, in main
    dv = Divine(args)
  File "[MASKED]/divine/gcn/bin/prioritize/divine.py", line 99, in __init__
    self.vcf,uargs.ped,uargs.proband_id)
  File "[MASKED]/divine/gcn/lib/utils/lib_ped.py", line 16, in check_consistency_ped_vcf
    family_parser = FamilyParser(family_file, family_type)
  File "build/bdist.linux-x86_64/egg/ped_parser/parser.py", line 102, in __init__
  File "build/bdist.linux-x86_64/egg/ped_parser/parser.py", line 211, in ped_parser
SyntaxError: ped line is in wrong format
```

Any ideas? Or do you have an example PED file I can compare to?

**Comment by cjhong** [comment]
The svn update as of 9/12/2018 resolves this issue. In summary, the updates cover

- ped_parser to be installed via setup.py
- fix a bug in calling ped_parser.FamilyParser()
- fix an issue when querying HPO IDs are not registered yet in the HPO database used in Divine (by simply filtering out). Soon or later, Divine HPO database will be updated.
- Add data resource necessary to run Divine
- Add an example trio sample (ped, hpo, and vcf file) into gcn/bin/prioritize/examples
- Some minor fixes

For those of you who installed Divine previously,
1) update your local copy with the latest commit
2) cd $DIVINE
3) python ./setup.py --install --update_db

**Comment by holtjma** [comment]
I got the new trio demo to work, and will model the real data after that.  Thanks for the updates!
