### ISSUE TITLE
configuration file requirments

### ISSUE THREAD

**Issue by hjafar** [hwanglab/divine#6]
I have install the Divine tool (https://github.com/hwanglab/divine/blob/master/documents/tutorial/divine_tutorial.md) but when I run the following command, I have got the error as shown below.
$ divine.py -v ./Pfeiffer.vcf -o ./Pfeiffer.noHpo

IOError: check [beta_fit = /home/genomic-lab/Documents/kfmc/tools/divine/gcndata/snv_training/clin_tr.dill] in the file [/home/genomic-lab/Documents/kfmc/tools/divine/gcn/config/divine.conf]

It is showing related to configuration file that needs the following files in database part.

[database]
ext_disease_to_gene = gcndata/hpo/ALL_SOURCES_disgnet_TYPICAL_FEATURES_diseases_to_genes_to_phenotypes.txt
beta_fit = gcndata/snv_training/clin_tr.dill
esp_to_gene = gcndata/stringDB/est2geneSymbol_20160306.tsv

What I should do to fix the issue.

Best regards,
Hussain

**Comment by cjhong** [comment]
Can you make sure whether the file (/home/genomic-lab/Documents/kfmc/tools/divine/gcndata/snv_training/clin_tr.dill) exists?

**Comment by hjafar** [comment]
Thanks for the fast replay.
It is not exists in the divine folder (snv_training). Also the rest files doesn't exists 
how can I get them?

**Comment by hjafar** [comment]
I am still waiting to receiving a response from you regarding list files databases above.
Thank you

**Comment by cjhong** [comment]
Sorry for the late reply.
Have you followed the installation instructions? You need to access AWS
files to install the resource files.

**Comment by hjafar** [comment]
I really appropriate for your reply.
I was trying to find another tool to similar to yours but I could not find to answer the biological question with WES data of complex inheritance diseases.
I still find difficultly to find and install all files in the config file... I did not find the "AWS" file to install the resource files.
Note: the tool is installed correctly when I run $ divine.py --help but some files are missing in the divine.conf file (i.e. [database]
ext_disease_to_gene =, beta_fit = and esp_to_gene = ) when I run the command line divine.py -v ./Pfeiffer.vcf -o ./Pfeiffer.noHpo
THNK

**Comment by cjhong** [comment]
Can you download the file at the link and try it?

https://drive.google.com/open?id=1_n9UFzKesRqyJqN5IVVO1LQ4HDaxl-Ad

Thank you,

**Comment by hjafar** [comment]
I really appropriate for your reply.
I was trying to find another tool to similar to yours but I could not find to answer the biological question with WES data of complex inheritance diseases.
I still find difficultly to find and install all files in the config file... I did not find the "AWS" file to install the resource files.
Note: the tool is installed correctly when I run $ divine.py --help but some files are missing in the divine.conf file (i.e. [database]
ext_disease_to_gene =, beta_fit = and esp_to_gene = ) when I run the command line divine.py -v ./Pfeiffer.vcf -o ./Pfeiffer.noHpo
THNK

**Comment by hjafar** [comment]
Good day...
Thank you for the quick response and for sending the request files.

I have run the following command line but I have got some issues as shown below. Could you please have look at and tell me how it can solve it.

$ divine.py -v '/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf' -o ./Pfeiffer.noHpo
############################################
2020-03-29 22:52:31.222536 [PART:<module>] Divine (v0.1.2) is running on [HPO:None ,VCF:/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf]

############################################
2020-03-29 22:52:31.222572 [INFO:Divine] initializing Divine ...

2020-03-29 22:52:31.222595 [INFO:_set_args] storing input condition ...

2020-03-29 22:52:31.222614 [INFO:_set_args] prepared log directory[./Pfeiffer.noHpo/logs]  ...

2020-03-29 22:52:31.222798 [INFO:<module>] reading configuration file [_read_config;/home/genomic-lab/Documents/kfmc/tools/divine/gcn/config/divine.conf] ...

2020-03-29 22:52:31.223093 [INFO:<module>] done. [_read_config]

2020-03-29 22:52:31.223143 [INFO:<module>] capturing user command line [record_commandline] ...

2020-03-29 22:52:31.223315 [INFO:<module>] done. [record_commandline]

2020-03-29 22:52:31.223345 [INFO:<module>] <divine> initialization completed [_set_args]

opening VCF [/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf] and parse heads ...
predicting gender from the sample [/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf]
gender identified [1], Done.
Sample ID [manuel] is identified for a proband analysis!
setting up damaging factors ...
2020-03-29 22:52:31.458824 [INFO:<module>] VCF is going to be masked by RefGene coding region

2020-03-29 22:52:31.458900 [INFO:<module>] done. initialization

2020-03-29 22:52:31.458922 [INFO:<module>] analyzing variants on [/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf] ...

2020-03-29 22:52:31.458959 [INFO:<module>] annotating VCF file[vannotate;/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf] ...

2020-03-29 22:52:31.459043 [INFO:<module>] creating a bed file[./Pfeiffer.noHpo/refGene_e20_so_merged.bed] containing RefGene coding region (cmpl/incmpl/unk) @ RefGeneUcscTB.create_bed

2020-03-29 22:52:32.302593 [INFO:<module>] sorting bed file ... @ RefGeneUcscTB.create_bed

2020-03-29 22:52:33.115626 [INFO:<module>] merging exon coordinates overlapped each other... @ RefGeneUcscTB.create_bed

2020-03-29 22:52:34.198943 [INFO:<module>] done. @ RefGeneUcscTB.create_bed

2020-03-29 22:52:34.202829 [INFO:<module>] extracting variants in coding region from [/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf] @ vannotate ...

2020-03-29 22:52:34.203170 [INFO:<module>] storing coding region boundaries from [./Pfeiffer.noHpo/refGene_e20_so_merged.bed] @ RefGeneUcscTB.get_boundary

2020-03-29 22:52:37.378357 [INFO:<module>] done. @ RefGeneUcscTB.get_boundary

2020-03-29 22:52:37.378608 [INFO:<module>] masking the vcf file [/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/examples/Pfeiffer.vcf] by the bed file [./Pfeiffer.noHpo/refGene_e20_so_merged.bed] @ BedMaskingVCF.run

2020-03-29 22:52:38.193988 [INFO:<module>] done. @ BedMaskingVCF.run

2020-03-29 22:52:38.194143 [INFO:<module>] done.@ vannotate

2020-03-29 22:52:38.194266 [INFO:<module>] python /home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py -i ./Pfeiffer.noHpo/refgene_e20.vcf -o ./Pfeiffer.noHpo/divine.vcf -l ./Pfeiffer.noHpo/logs

retcode: 1
Traceback (most recent call last):
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/divine.py", line 1415, in <module>
    main()
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/divine.py", line 1369, in main
    dv.vannotate(args.reuse)
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/prioritize/divine.py", line 481, in vannotate
    lib_utils.runcmd2(cmd,self.log_dir,self.logger,job_name)
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/lib/utils/lib_utils.py", line 208, in runcmd2
    raise RuntimeError('[%s] failed' % cmd_str)
RuntimeError: [python /home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py -i ./Pfeiffer.noHpo/refgene_e20.vcf -o ./Pfeiffer.noHpo/divine.vcf -l ./Pfeiffer.noHpo/logs] failed

************************************************************************
When I have run the annotpipe.py script I have got the follwoing massage.

$ '/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py' --help
/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py: line 11: $'\n.. module:: annotpipe\n\t:platform: Unix, Windows, MacOSX\n\t:synopsis: A wraper to call VARANT\n\n.. moduleauthor:: Kunal Kundu (kunal.kundu@tcs.com); modified by changjin.hong@gmail.com\n\nThis modules is a wrapper to call VARANT. The inputs are -\n1. Unannotated VCF file path\n2. Path to create annotated vcf file (Option)\n': command not found

I look forward to hearing from you soon.

Thank you so much in advance...

**Comment by cjhong** [comment]
Run this and send log files in the "./Pfeiffer.noHpo/logs" to me.

python /home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py -i ./Pfeiffer.noHpo/refgene_e20.vcf -o ./Pfeiffer.noHpo/divine.vcf -l ./Pfeiffer.noHpo/logs

**Comment by hjafar** [comment]
Here's the the output after run the above command line:

$ python /home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py -i '/home/genomic-lab/Documents/kfmc/tools/divine/Pfeiffer.noHpo/refgene_e20.vcf' -o ./Pfeiffer.noHpo/divine.vcf -l ./Pfeiffer.noHpo/logs
Annotation on [/home/genomic-lab/Documents/kfmc/tools/divine/Pfeiffer.noHpo/refgene_e20.vcf] in progress. Be patient (30 min+) ...
Traceback (most recent call last):
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py", line 118, in <module>
    main()
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py", line 115, in main
    ap.annotate_varant()
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/bin/annotpipe.py", line 83, in annotate_varant
    annotator.main(self.invcf, self.outvcf, self.logger, options)
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/lib/varann/vartype/varant/annotator.py", line 1369, in main
    snpa = SNPAnnotation(options)
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/lib/varann/vartype/varant/annotator.py", line 85, in __init__
    self.omim = self.mimdb.load_omim()
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/lib/databases/omim.py", line 44, in load_omim
    results = self.execute(stmt).fetchall()
  File "/home/genomic-lab/Documents/kfmc/tools/divine/gcn/lib/io/db.py", line 243, in execute
    return cursor.execute(stmt)
sqlite3.OperationalError: no such table: mimdis

*****************************************************************************************
The following the output of /Pfeiffer.noHpo/logs file. Also, I have attaced the file.

2020-03-30 15:36:08,684 - gcn - INFO - Environment variable check successful..
2020-03-30 15:36:08,684 - gcn - INFO - Input file = /home/genomic-lab/Documents/kfmc/tools/divine/Pfeiffer.noHpo/refgene_e20.vcf, Output file = ./Pfeiffer.noHpo/divine.vcf
[varant_20200330_1536.log](https://github.com/hwanglab/divine/files/4402771/varant_20200330_1536.log)

**Comment by cjhong** [comment]
Can you make sure that you set up a database all properly?
1.
My setup for gcndb looks like
??@??:divine$ ls gcndb
clinvardb               
clnphesnpdb  
dbsnp  
exac          
interpro  
mimdb  
nsfpdb   
refmrna     
splicedb
clinvitae               
cosmic       
esp    
geneontology  
kgdb      
mirna  
refgene  
regulomedb  
utrdb

2. Or, did you add all shell environment configuration after installation?

3. Let us communicate via email (changjin.hong@gmail.com) directly?

4. The other option is to use exomiser which is also available for WES germline annotation.

**Comment by hjafar** [comment]
Thank you so much.
please check your email.
